"""Comment Model Create

Revision ID: 9d7f9a77c780
Revises:
Create Date: 2026-04-05 01:32:28.241960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d7f9a77c780"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("post_uid", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("parent_uid", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )

    op.create_index(
        op.f("ix_comments_post_uid"), "comments", ["post_uid"], unique=False
    )
    op.create_index(
        op.f("ix_comments_user_uid"), "comments", ["user_uid"], unique=False
    )
    op.create_index(
        op.f("ix_comments_parent_uid"), "comments", ["parent_uid"], unique=False
    )

    op.create_foreign_key(
        "fk_comments_parent_uid",
        "comments",
        "comments",
        ["parent_uid"],
        ["uid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_user_uid"), table_name="comments")
    op.drop_index(op.f("ix_comments_uid"), table_name="comments")
    op.drop_index(op.f("ix_comments_post_uid"), table_name="comments")
    op.drop_index(op.f("ix_comments_parent_uid"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
