"""Like Model Create

Revision ID: c1613b141338
Revises: 9d7f9a77c780
Create Date: 2026-04-06 17:44:11.743840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1613b141338'
down_revision: Union[str, Sequence[str], None] = '9d7f9a77c780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('post_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_post_uid'), 'likes', ['post_uid'], unique=False)
    op.create_index(op.f('ix_likes_uid'), 'likes', ['uid'], unique=True)
    op.create_index(op.f('ix_likes_user_uid'), 'likes', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_user_uid'), table_name='likes')
    op.drop_index(op.f('ix_likes_uid'), table_name='likes')
    op.drop_index(op.f('ix_likes_post_uid'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
